# Default Iris settings for a new Cobble Music client. Once installed, this file is player-owned.
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=5
shaderPack=Max Quality (Iteration RP - Path Traced)
