using CobbleMusicUpdater;

// Updater 1.2.20 (Kewz's friends, 2026-09-23: "Pre-Launch command failed with code 3"). Convergence tolerates a runtime-rewritten
// signed config once its signed revision was delivered, but the commit check still demanded its exact signed bytes, so every
// update after the game had rewritten config/gravels-extended-battles.toml rolled back with "Adopted managed file changed before
// commit" and blocked the launch.
internal static partial class Program
{
    private static async Task TestCatalogRuntimeMutableConfigCommitAsync(string root, ConvergenceTestSigner signer)
    {
        UpdaterPaths paths = Paths(root);
        var configuration = new UpdaterConfiguration { AllowedRoots = ["mods", "config", "resourcepacks"] };
        const string requiredPath = "mods/runtime-regression.jar";
        const string tomlPath = "config/gravels-extended-battles.toml";
        const string rpoPath = "resourcepacks/Fresh Food.zip.rpo";
        byte[] required = ConvergenceFabricJar("runtime_regression", "2.0.0");
        byte[] signedToml = System.Text.Encoding.UTF8.GetBytes("[battle]\nshowTypes = true\n");
        byte[] runtimeToml = System.Text.Encoding.UTF8.GetBytes("# regenerated by Gravel's Extended Battles\n[battle]\nshowTypes = true\nnewKey = 1\n");
        byte[] signedRpo = System.Text.Encoding.UTF8.GetBytes("{\"overlays\":[]}");
        byte[] runtimeRpo = System.Text.Encoding.UTF8.GetBytes("{\"overlays\":[],\"lastSeen\":1790200000}");
        RemoteRelease latest = await CreateSignedConvergenceReleaseAsync(paths, new UpdateManifest
        {
            SchemaVersion = 1, Version = "1.0.9",
            Files = [ConvergenceFile(requiredPath, required), ConvergenceFile(tomlPath, signedToml), ConvergenceFile(rpoPath, signedRpo)]
        }, new() { [requiredPath] = required, [tomlPath] = signedToml, [rpoPath] = signedRpo }, signer, configuration);

        // The signed revisions were delivered earlier (state records them); since then the game rewrote both files,
        // and the required jar needs a repair, which forces a real transaction commit.
        byte[] corrupted = required.ToArray();
        corrupted[^1] ^= 1;
        await WriteConvergenceFileAsync(paths, requiredPath, corrupted);
        await WriteConvergenceFileAsync(paths, tomlPath, runtimeToml);
        await WriteConvergenceFileAsync(paths, rpoPath, runtimeRpo);
        await LocalStateStore.SaveStateAsync(paths, StateFrom(latest.Manifest, latest.ManifestSha256), NoCancellation);

        var logs = new List<string>();
        await new UpdateEngine(paths, configuration, logs.Add, verifiedCatalog: [latest]).CheckAndUpdateAsync([], checkOnly: false, NoCancellation);

        Equal(HashBytes(required), await PathSafety.Sha256Async(PathSafety.CombineUnder(paths.MinecraftDirectory, requiredPath), NoCancellation),
            "the corrupted managed jar is repaired in the same commit");
        Equal(HashBytes(runtimeToml), await PathSafety.Sha256Async(PathSafety.CombineUnder(paths.MinecraftDirectory, tomlPath), NoCancellation),
            "the game's rewritten GEB TOML is kept, not blocked on");
        Equal(HashBytes(runtimeRpo), await PathSafety.Sha256Async(PathSafety.CombineUnder(paths.MinecraftDirectory, rpoPath), NoCancellation),
            "the game's rewritten .rpo is kept, not blocked on");
        Equal(false, File.Exists(TransactionStore.JournalPath(paths)), "the commit finishes its journal");
        Equal(false, logs.Any(line => line.Contains("changed before commit", StringComparison.Ordinal)), "no pre-commit rejection");
        Console.WriteLine("Runtime-mutable config commit check passed: rewritten GEB TOML and .rpo tolerated at commit, repair committed.");
    }
}
